const globals = require('globals');
const tsEslintParser = require('@typescript-eslint/parser');
const pluginTsEslint = require('@typescript-eslint/eslint-plugin');
const pluginImport = require('eslint-plugin-import-x');
const pluginImportNewLines = require('eslint-plugin-import-newlines');
// eslint-plugin-n ships as an ESM module with a default export; under plain
// require() that surfaces as { default: <plugin> } instead of the plugin itself.
const pluginN = require('eslint-plugin-n').default;
const pluginPromise = require('eslint-plugin-promise');
const pluginUnusedImports = require('eslint-plugin-unused-imports');
const stylesPlugin = require('@stylistic/eslint-plugin');
const jestPlugin = require('eslint-plugin-jest');
const pluginReact = require('eslint-plugin-react');
const pluginReactHooks = require('eslint-plugin-react-hooks');

module.exports = {
  languageOptions: {
    globals: {
      ...globals.browser,
      ...globals.node,
      ...jestPlugin.environments.globals.globals,
    },
    ecmaVersion: 2022,
    parser: tsEslintParser,
    parserOptions: {
      ecmaFeatures: { jsx: true },
    },
  },

  settings: {
    react: { version: 'detect' },
  },

  files: ['src/**/*.{ts,tsx}'],

  ignores: [
    'node_modules/**',
    'build/**',
    'dist/**',
    'eslint.config.cjs',
    'src/tmp/**',
    'src/temp/**',
  ],

  plugins: {
    import: pluginImport,
    n: pluginN,
    promise: pluginPromise,
    '@typescript-eslint': pluginTsEslint,
    'import-newlines': pluginImportNewLines,
    'unused-imports': pluginUnusedImports,
    '@stylistic': stylesPlugin,
    jest: jestPlugin,
    react: pluginReact,
    'react-hooks': pluginReactHooks,
  },

  rules: {
    'object-shorthand': ['warn', 'properties'],
    'accessor-pairs': ['error', {
      setWithoutGet: true,
      enforceForClassMembers: true,
    }],
    'array-bracket-spacing': ['error', 'never'],
    'array-callback-return': ['error', {
      allowImplicit: false,
      checkForEach: false,
    }],
    'arrow-spacing': ['error', {
      before: true,
      after: true,
    }],
    'block-spacing': ['error', 'always'],
    'brace-style': ['error', '1tbs', { allowSingleLine: false }],
    'comma-spacing': ['error', {
      before: false,
      after: true,
    }],
    'comma-style': ['error', 'last'],
    'computed-property-spacing': ['error', 'never', { enforceForClassMembers: true }],
    'constructor-super': 'error',
    'default-case-last': 'error',
    'dot-location': ['error', 'property'],
    'eol-last': 'error',
    'func-call-spacing': ['error', 'never'],
    'generator-star-spacing': ['error', {
      before: true,
      after: true,
    }],
    'key-spacing': ['error', {
      beforeColon: false,
      afterColon: true,
    }],
    'keyword-spacing': ['error', {
      before: true,
      after: true,
    }],
    'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],
    'multiline-ternary': ['error', 'always-multiline'],
    'new-cap': ['warn', {
      newIsCap: true,
      capIsNew: false,
      properties: true,
    }],
    'new-parens': 'error',
    'no-array-constructor': 'error',
    'no-async-promise-executor': 'error',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-constant-condition': ['error', { checkLoops: false }],
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-useless-backreference': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-eval': 'error',
    'no-ex-assign': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-boolean-cast': 'error',
    'no-extra-parens': ['error', 'functions'],
    'no-fallthrough': 'error',
    'no-floating-decimal': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-implied-eval': 'error',
    'no-import-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-iterator': 'error',
    'no-labels': ['error', {
      allowLoop: false,
      allowSwitch: false,
    }],
    'no-lone-blocks': 'off',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-prototype-builtins': 'error',
    'no-useless-catch': 'error',
    'no-mixed-operators': ['error', {
      groups: [
        ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
        ['&&', '||'],
        ['in', 'instanceof'],
      ],
      allowSamePrecedence: true,
    }],
    'no-mixed-spaces-and-tabs': 'error',
    'no-multi-spaces': 'off',
    'no-multi-str': 'error',
    'no-multiple-empty-lines': ['error', {
      max: 1,
      maxBOF: 0,
      maxEOF: 0,
    }],
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-object': 'error',
    'no-new-symbol': 'error',
    'no-new-wrappers': 'error',
    'no-obj-calls': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    'no-proto': 'error',
    'no-redeclare': ['error', { builtinGlobals: false }],
    'no-regex-spaces': 'error',
    'no-return-assign': ['error', 'except-parens'],
    'no-self-assign': ['error', { props: true }],
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-tabs': 'error',
    'no-template-curly-in-string': 'error',
    'no-this-before-super': 'error',
    'no-throw-literal': 'error',
    'no-trailing-spaces': 'error',
    'no-undef': 'off',
    'no-undef-init': 'error',
    'no-unexpected-multiline': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unneeded-ternary': ['error', { defaultAssignment: false }],
    'no-unreachable': 'error',
    'no-unreachable-loop': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-use-before-define': ['error', {
      functions: false,
      classes: false,
      variables: false,
    }],
    'no-useless-call': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-escape': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-void': 'error',
    'no-whitespace-before-property': 'error',
    'no-with': 'error',
    'object-curly-newline': ['error', {
      multiline: true,
      consistent: true,
    }],
    'object-curly-spacing': ['error', 'always'],
    'object-property-newline': ['error', { allowMultiplePropertiesPerLine: true }],
    'one-var': ['error', { initialized: 'never' }],
    'operator-linebreak': ['error', 'after', {
      overrides: {
        '?': 'before',
        ':': 'before',
        '|>': 'before',
      },
    }],
    'padded-blocks': ['error', {
      blocks: 'never',
      switches: 'never',
      classes: 'never',
    }],
    'prefer-promise-reject-errors': 'error',
    'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
    'quote-props': ['error', 'as-needed'],
    'rest-spread-spacing': ['error', 'never'],
    'semi-spacing': ['error', {
      before: false,
      after: true,
    }],
    'space-before-blocks': ['error', 'always'],
    'space-before-function-paren': ['off'],
    'space-in-parens': ['error', 'never'],
    'space-infix-ops': 'error',
    'space-unary-ops': ['error', {
      words: true,
      nonwords: false,
    }],
    'symbol-description': 'error',
    'template-curly-spacing': ['error', 'never'],
    'template-tag-spacing': ['error', 'never'],
    'unicode-bom': ['error', 'never'],
    'use-isnan': ['error', {
      enforceForSwitchCase: true,
      enforceForIndexOf: true,
    }],
    'valid-typeof': ['error', { requireStringLiterals: true }],
    'wrap-iife': ['error', 'any', { functionPrototypeMethods: true }],
    'yield-star-spacing': ['error', 'both'],
    yoda: ['error', 'never'],

    'import/export': 'error',
    'import/first': 'error',
    'import/no-absolute-path': ['error', {
      esmodule: true,
      commonjs: true,
      amd: false,
    }],
    'import/no-duplicates': 'error',
    'import/no-named-default': 'error',
    'import/no-webpack-loader-syntax': 'error',
    'import-newlines/enforce': ['error', {
      items: 3,
      'max-len': 110,
    }],
    'import/order': ['error', {
      alphabetize: { order: 'ignore' },
      groups: [
        'builtin',
        'external',
        'internal',
        'parent',
        ['sibling', 'index'],
      ],
      'newlines-between': 'ignore',
      pathGroupsExcludedImportTypes: ['builtin'],
    }],
    'n/handle-callback-err': ['error', '^(err|error)$'],
    'n/no-callback-literal': 'error',
    'n/no-deprecated-api': 'error',
    'n/no-exports-assign': 'error',
    'n/no-new-require': 'error',
    'n/no-path-concat': 'error',
    'n/process-exit-as-throw': 'error',
    semi: 'off',
    'arrow-body-style': 'off',
    'comma-dangle': [
      'error',
      'always-multiline',
    ],
    camelcase: 'off',
    curly: 'error',
    'dot-notation': 'off',
    eqeqeq: ['error', 'smart'],
    'guard-for-in': 'error',
    'id-blacklist': 'off',
    'id-match': 'off',
    'max-len': ['error', { code: 120 }],
    'no-bitwise': 'error',
    'no-console': 'off',
    'no-empty': 'off',
    'no-shadow': 'off',
    'no-underscore-dangle': 'off',
    'no-unused-labels': 'error',
    'no-unused-vars': 'off',
    'no-unused-private-class-members': 'warn',
    'no-unused-expressions': 'off',
    'no-var': 'error',
    'prefer-const': 'error',
    quotes: ['error', 'single'],
    radix: 'error',
    // markers: ['/'] exempts /// <reference .../> triple-slash directives (vite-env.d.ts).
    'spaced-comment': ['error', 'always', { markers: ['/'] }],
    'promise/param-names': 'off',
    'newline-before-return': 'off',
    indent: 'off',
    'padding-line-between-statements': 'off',
    'unused-imports/no-unused-imports': 'warn',
    'unused-imports/no-unused-vars': ['warn', {
      vars: 'all',
      varsIgnorePattern: '^_',
      args: 'after-used',
      caughtErrors: 'all',
      caughtErrorsIgnorePattern: '^_',
      argsIgnorePattern: '^_',
    }],
    'max-depth': ['error', 4],
    '@typescript-eslint/consistent-type-definitions': 'error',
    '@typescript-eslint/explicit-member-accessibility': [
      'error',
      {
        accessibility: 'explicit',
        overrides: {
          accessors: 'explicit',
          constructors: 'no-public',
          methods: 'explicit',
          properties: 'explicit',
          parameterProperties: 'explicit',
        },
      },
    ],
    '@stylistic/member-delimiter-style': ['error', {
      multiline: { delimiter: 'semi', requireLast: true },
      singleline: { delimiter: 'semi', requireLast: false },
    }],
    '@stylistic/semi': ['error', 'always'],
    '@typescript-eslint/member-ordering': 'error',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/no-useless-constructor': 'off',
    '@typescript-eslint/no-empty-interface': 'error',
    '@typescript-eslint/no-inferrable-types': 'off',
    '@typescript-eslint/no-misused-new': 'error',
    '@typescript-eslint/no-non-null-assertion': 'error',
    '@typescript-eslint/no-use-before-define': 'error',
    '@typescript-eslint/prefer-function-type': 'error',
    '@stylistic/type-annotation-spacing': 'error',
    '@typescript-eslint/unified-signatures': 'error',
    '@typescript-eslint/no-shadow': 'error',
    '@stylistic/indent': ['error', 2, {
      SwitchCase: 1,
      ignoredNodes: [
        'TSIntersectionType',
        'TSUnionType',
        'TSTypeParameterInstantiation',
        'FunctionExpression > .params[decorators.length > 0]',
        'FunctionExpression > .params > :matches(Decorator, :not(:first-child))',
        'ClassBody.body > PropertyDefinition[decorators.length > 0] > .key',
      ],
    }],
    '@typescript-eslint/explicit-module-boundary-types': ['error'],
    '@typescript-eslint/no-explicit-any': ['error'],
    '@typescript-eslint/explicit-function-return-type': ['off'],
    '@stylistic/padding-line-between-statements': [
      'error',
      { blankLine: 'always', prev: 'block-like', next: 'if' },
      { blankLine: 'always', prev: 'expression', next: 'if' },
      { blankLine: 'always', prev: 'block-like', next: '*' },
    ],
    '@typescript-eslint/typedef': [
      'warn',
      {
        variableDeclaration: true,
        variableDeclarationIgnoreFunction: true,
      },
    ],
    '@stylistic/space-before-function-paren': [
      'warn',
      {
        anonymous: 'always',
        named: 'always',
        asyncArrow: 'always',
      },
    ],

    // React: rules not covered by the no-jsx-scope runtime (React 19 automatic
    // JSX transform — `React` does not need to be in scope) are left out.
    'react/display-name': 'error',
    'react/jsx-key': 'error',
    'react/jsx-no-comment-textnodes': 'error',
    'react/jsx-no-duplicate-props': 'error',
    'react/jsx-no-target-blank': 'error',
    'react/jsx-no-undef': 'error',
    'react/jsx-uses-vars': 'error',
    'react/no-children-prop': 'error',
    'react/no-danger-with-children': 'error',
    'react/no-deprecated': 'error',
    'react/no-direct-mutation-state': 'error',
    'react/no-find-dom-node': 'error',
    'react/no-is-mounted': 'error',
    'react/no-render-return-value': 'error',
    'react/no-string-refs': 'error',
    'react/no-unescaped-entities': 'error',
    'react/no-unknown-property': 'error',
    'react/require-render-return': 'error',
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/exhaustive-deps': 'warn',
  },
};
